# Generated by Django 4.2.2 on 2023-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='media/breakfast')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='media/dinner')),
            ],
        ),
        migrations.CreateModel(
            name='LunchItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='media/lunch')),
            ],
        ),
    ]
