# Generated by Django 4.2.2 on 2023-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfastitems',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='dinneritems',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='lunchitems',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='breakfastitems',
            name='Image',
            field=models.ImageField(blank=None, max_length=300, null=True, upload_to='media/breakfast'),
        ),
        migrations.AlterField(
            model_name='dinneritems',
            name='Image',
            field=models.ImageField(blank=None, max_length=300, null=True, upload_to='media/dinner'),
        ),
        migrations.AlterField(
            model_name='lunchitems',
            name='Image',
            field=models.ImageField(blank=None, max_length=300, null=True, upload_to='media/lunch'),
        ),
    ]
