# Generated by Django 4.2.2 on 2023-06-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_title_breakfastitems_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfastitems',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dinneritems',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lunchitems',
            old_name='Title',
            new_name='title',
        ),
    ]
