# Generated by Django 4.2.1 on 2023-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_title_breakfastitems_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarasolItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Image', models.ImageField(blank=None, max_length=300, null=True, upload_to='media/carasol')),
            ],
        ),
    ]
