# Generated by Django 4.2.1 on 2023-07-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_carasolitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakfastItems',
            new_name='BreakfastItem',
        ),
        migrations.RenameModel(
            old_name='CarasolItems',
            new_name='CarasolItem',
        ),
        migrations.RenameModel(
            old_name='DinnerItems',
            new_name='DinnerItem',
        ),
        migrations.RenameModel(
            old_name='LunchItems',
            new_name='LunchItem',
        ),
    ]
